name: {{ cookiecutter.project_slug_no_hyphen }}
channels:
  - defaults
  - conda-forge
  - nvidia
dependencies:
  - nvidia::cudatoolkit=11.2.72
  - defaults::python=3.8.5
  - defaults::boto3==1.17.109
  - conda-forge::rich=10.11.0
  - conda-forge::mlflow=1.20.2
  - conda-forge::tensorboardx=2.2
  - pip
  - pip:
    - tensorflow==2.6.0  # not yet on Conda with full GPU support
    - tensorflow_datasets==4.2.0
    - pycuda==2021.1  # not on Conda
    - system-intelligence==2.0.2  # not yet on Conda
