name: Sync mlf-core project

on:
  schedule:
    - cron: '0 1 * * *' # 1 am UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Setup Python
          uses: actions/setup-python@v1
          with:
            python-version: 3.8

        - name: Install mlf-core
          run: pip install mlf-core

        - uses: actions/checkout@v2
          name: Check out source-code repository
          with:
              fetch-depth: 0
              token: {% raw %}${{ secrets.MLF_CORE_SYNC_TOKEN }}{% endraw %}

        - uses: oleksiyrudenko/gha-git-credentials@v2
          with:
               name: '{{ cookiecutter.creator_github_username }}'
               email: '{{ cookiecutter.email }}'
               actor: '{{ cookiecutter.creator_github_username }}'
               token: '{% raw %}${{ secrets.MLF_CORE_SYNC_TOKEN }}{% endraw %}'

        - name: Sync project
          run: mlf-core --verbose sync . {% raw %}${{ secrets.MLF_CORE_SYNC_TOKEN }}{% endraw %} {{ cookiecutter.creator_github_username }}
