name: Create mlflow_pytorch Template

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./exploding_springfield
    strategy:
      matrix:
        python: [3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
        name: Check out source-code repository
        with:
            path: ../

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Build mlf-core
        run: |
          cd ../mlf_core
          make install

      - name: Create mlflow-pytorch Template
        run: |
          echo -e "\n\n\n\n\nn\n\n\n\nn" | mlf-core create

      - name: debug
        run: |
          pwd
          ls -la

      - name: Build Docker container
        uses: docker/build-push-action@v1
        with:
          repository: mlfcore/exploding_springfield
          tags: 0.1.0-SNAPSHOT
          push: false

      - name: Install mlflow
        run: pip install mlflow

      - name: Train on the CPU
        run: |
          cd exploding_springfield
          mlflow run exploding_springfield
